/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAuthStatusRouteImport } from './routes/api/auth/status'
import { Route as ApiBillingConfigRouteImport } from './routes/api/billing/config'
import { Route as ApiBillingLemonRouteImport } from './routes/api/billing/lemon'
import { Route as ApiOauthClaimRouteImport } from './routes/api/oauth/claim'
import { Route as ApiOauthDoneRouteImport } from './routes/api/oauth/done'
import { Route as ApiOauthStartRouteImport } from './routes/api/oauth/start'
import { Route as ApiUserAlertsRouteImport } from './routes/api/user/alerts'
import { Route as ApiUserPlanRouteImport } from './routes/api/user/plan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthStatusRoute = ApiAuthStatusRouteImport.update({
  id: '/api/auth/status',
  path: '/api/auth/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingConfigRoute = ApiBillingConfigRouteImport.update({
  id: '/api/billing/config',
  path: '/api/billing/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingLemonRoute = ApiBillingLemonRouteImport.update({
  id: '/api/billing/lemon',
  path: '/api/billing/lemon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthClaimRoute = ApiOauthClaimRouteImport.update({
  id: '/api/oauth/claim',
  path: '/api/oauth/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthDoneRoute = ApiOauthDoneRouteImport.update({
  id: '/api/oauth/done',
  path: '/api/oauth/done',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthStartRoute = ApiOauthStartRouteImport.update({
  id: '/api/oauth/start',
  path: '/api/oauth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserAlertsRoute = ApiUserAlertsRouteImport.update({
  id: '/api/user/alerts',
  path: '/api/user/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserPlanRoute = ApiUserPlanRouteImport.update({
  id: '/api/user/plan',
  path: '/api/user/plan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/status': typeof ApiAuthStatusRoute
  '/api/billing/config': typeof ApiBillingConfigRoute
  '/api/billing/lemon': typeof ApiBillingLemonRoute
  '/api/oauth/claim': typeof ApiOauthClaimRoute
  '/api/oauth/done': typeof ApiOauthDoneRoute
  '/api/oauth/start': typeof ApiOauthStartRoute
  '/api/user/alerts': typeof ApiUserAlertsRoute
  '/api/user/plan': typeof ApiUserPlanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/status': typeof ApiAuthStatusRoute
  '/api/billing/config': typeof ApiBillingConfigRoute
  '/api/billing/lemon': typeof ApiBillingLemonRoute
  '/api/oauth/claim': typeof ApiOauthClaimRoute
  '/api/oauth/done': typeof ApiOauthDoneRoute
  '/api/oauth/start': typeof ApiOauthStartRoute
  '/api/user/alerts': typeof ApiUserAlertsRoute
  '/api/user/plan': typeof ApiUserPlanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/status': typeof ApiAuthStatusRoute
  '/api/billing/config': typeof ApiBillingConfigRoute
  '/api/billing/lemon': typeof ApiBillingLemonRoute
  '/api/oauth/claim': typeof ApiOauthClaimRoute
  '/api/oauth/done': typeof ApiOauthDoneRoute
  '/api/oauth/start': typeof ApiOauthStartRoute
  '/api/user/alerts': typeof ApiUserAlertsRoute
  '/api/user/plan': typeof ApiUserPlanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/auth/$'
    | '/api/auth/status'
    | '/api/billing/config'
    | '/api/billing/lemon'
    | '/api/oauth/claim'
    | '/api/oauth/done'
    | '/api/oauth/start'
    | '/api/user/alerts'
    | '/api/user/plan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/auth/$'
    | '/api/auth/status'
    | '/api/billing/config'
    | '/api/billing/lemon'
    | '/api/oauth/claim'
    | '/api/oauth/done'
    | '/api/oauth/start'
    | '/api/user/alerts'
    | '/api/user/plan'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/auth/$'
    | '/api/auth/status'
    | '/api/billing/config'
    | '/api/billing/lemon'
    | '/api/oauth/claim'
    | '/api/oauth/done'
    | '/api/oauth/start'
    | '/api/user/alerts'
    | '/api/user/plan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthStatusRoute: typeof ApiAuthStatusRoute
  ApiBillingConfigRoute: typeof ApiBillingConfigRoute
  ApiBillingLemonRoute: typeof ApiBillingLemonRoute
  ApiOauthClaimRoute: typeof ApiOauthClaimRoute
  ApiOauthDoneRoute: typeof ApiOauthDoneRoute
  ApiOauthStartRoute: typeof ApiOauthStartRoute
  ApiUserAlertsRoute: typeof ApiUserAlertsRoute
  ApiUserPlanRoute: typeof ApiUserPlanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/status': {
      id: '/api/auth/status'
      path: '/api/auth/status'
      fullPath: '/api/auth/status'
      preLoaderRoute: typeof ApiAuthStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/config': {
      id: '/api/billing/config'
      path: '/api/billing/config'
      fullPath: '/api/billing/config'
      preLoaderRoute: typeof ApiBillingConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/lemon': {
      id: '/api/billing/lemon'
      path: '/api/billing/lemon'
      fullPath: '/api/billing/lemon'
      preLoaderRoute: typeof ApiBillingLemonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/claim': {
      id: '/api/oauth/claim'
      path: '/api/oauth/claim'
      fullPath: '/api/oauth/claim'
      preLoaderRoute: typeof ApiOauthClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/done': {
      id: '/api/oauth/done'
      path: '/api/oauth/done'
      fullPath: '/api/oauth/done'
      preLoaderRoute: typeof ApiOauthDoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/start': {
      id: '/api/oauth/start'
      path: '/api/oauth/start'
      fullPath: '/api/oauth/start'
      preLoaderRoute: typeof ApiOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/alerts': {
      id: '/api/user/alerts'
      path: '/api/user/alerts'
      fullPath: '/api/user/alerts'
      preLoaderRoute: typeof ApiUserAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/plan': {
      id: '/api/user/plan'
      path: '/api/user/plan'
      fullPath: '/api/user/plan'
      preLoaderRoute: typeof ApiUserPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthStatusRoute: ApiAuthStatusRoute,
  ApiBillingConfigRoute: ApiBillingConfigRoute,
  ApiBillingLemonRoute: ApiBillingLemonRoute,
  ApiOauthClaimRoute: ApiOauthClaimRoute,
  ApiOauthDoneRoute: ApiOauthDoneRoute,
  ApiOauthStartRoute: ApiOauthStartRoute,
  ApiUserAlertsRoute: ApiUserAlertsRoute,
  ApiUserPlanRoute: ApiUserPlanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
